export const MOCK_CITIES = [
  {
    id: 'city-1',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    costIndex: '₹₹₹',
    costPerDay: 15000,
    popularity: 98,
    bestSeason: 'Spring / Autumn (Apr-Oct)',
    climate: 'Temperate',
    language: 'French',
    currency: 'EUR',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    description: 'The City of Light dazzles with iconic monuments like the Eiffel Tower, world-class art museums, charming bistros, and romantic Seine riverside walks.',
    tags: ['Culture', 'Romance', 'Food', 'Museums', 'Architecture'],
  },
  {
    id: 'city-2',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    costIndex: '₹₹₹',
    costPerDay: 13500,
    popularity: 96,
    bestSeason: 'Spring & Autumn (Mar-May, Sep-Nov)',
    climate: 'Subtropical',
    language: 'Japanese',
    currency: 'JPY',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    description: 'An electrifying metropolis harmonizing futuristic neon skylines with serene historic shrines, cutting-edge tech, and culinary perfection.',
    tags: ['Tech', 'Food', 'Nightlife', 'Culture', 'Temples'],
  },
  {
    id: 'city-3',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    costIndex: '₹₹',
    costPerDay: 11500,
    popularity: 94,
    bestSeason: 'Apr-Jun & Sep-Oct',
    climate: 'Mediterranean',
    language: 'Italian',
    currency: 'EUR',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    description: 'An open-air living museum packed with millennia of history, from the Colosseum and Vatican City to vibrant piazzas and authentic trattorias.',
    tags: ['History', 'Architecture', 'Food', 'Culture'],
  },
  {
    id: 'city-4',
    name: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    costIndex: '₹₹₹',
    costPerDay: 19000,
    popularity: 88,
    bestSeason: 'Jun-Sep (Summer) or Dec-Feb (Winter)',
    climate: 'Alpine',
    language: 'German',
    currency: 'CHF',
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=800&q=80',
    description: 'Nestled by pristine Lake Zurich and the Swiss Alps, boasting medieval streets, luxury boutiques, and unbeatable scenic mountain railways.',
    tags: ['Mountains', 'Nature', 'Luxury', 'Lakes'],
  },
  {
    id: 'city-5',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    costIndex: '₹₹',
    costPerDay: 10500,
    popularity: 92,
    bestSeason: 'Mar-May (Cherry Blossoms) & Nov',
    climate: 'Temperate',
    language: 'Japanese',
    currency: 'JPY',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'The cultural heart of Japan with over 1,000 Buddhist temples, tranquil Zen gardens, traditional geisha districts, and bamboo forests.',
    tags: ['Culture', 'Temples', 'Nature', 'Photography'],
  },
  {
    id: 'city-6',
    name: 'Bali (Ubud)',
    country: 'Indonesia',
    region: 'Asia',
    costIndex: '₹',
    costPerDay: 5500,
    popularity: 95,
    bestSeason: 'May-Sep (Dry Season)',
    climate: 'Tropical',
    language: 'Indonesian',
    currency: 'IDR',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    description: 'A spiritual and wellness paradise framed by emerald rice terraces, sacred Hindu water temples, waterfalls, and vibrant arts and crafts.',
    tags: ['Beaches', 'Wellness', 'Nature', 'Adventure', 'Budget-Friendly'],
  },
  {
    id: 'city-7',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    costIndex: '₹₹',
    costPerDay: 11000,
    popularity: 93,
    bestSeason: 'May-Jun & Sep-Oct',
    climate: 'Mediterranean',
    language: 'Spanish / Catalan',
    currency: 'EUR',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=80',
    description: 'A sun-drenched coastal city renowned for Gaudí’s surreal architecture, Mediterranean beaches, lively tapas bars, and Gothic Quarter alleys.',
    tags: ['Architecture', 'Beaches', 'Nightlife', 'Food'],
  },
  {
    id: 'city-8',
    name: 'New York City',
    country: 'United States',
    region: 'Americas',
    costIndex: '₹₹₹',
    costPerDay: 20000,
    popularity: 97,
    bestSeason: 'Apr-Jun & Sep-Nov',
    climate: 'Humid Continental',
    language: 'English',
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
    description: 'The energetic cultural capital featuring Broadway theaters, Central Park, legendary museums, diverse neighborhoods, and an iconic skyline.',
    tags: ['City', 'Shopping', 'Museums', 'Nightlife', 'Food'],
  },
  {
    id: 'city-9',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    costIndex: '₹',
    costPerDay: 6200,
    popularity: 89,
    bestSeason: 'Nov-Mar (Summer)',
    climate: 'Mediterranean',
    language: 'English / Afrikaans',
    currency: 'ZAR',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
    description: 'Dramatic coastal scenery beneath Table Mountain, pristine white beaches, historic wine estates, and penguin colonies.',
    tags: ['Nature', 'Adventure', 'Wine', 'Beaches', 'Budget-Friendly'],
  },
  {
    id: 'city-10',
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    costIndex: '₹₹₹',
    costPerDay: 16000,
    popularity: 91,
    bestSeason: 'Sep-Nov & Mar-May',
    climate: 'Temperate',
    language: 'English',
    currency: 'AUD',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
    description: 'Harbor city famous for the Sydney Opera House, Harbour Bridge, Bondi Beach surf culture, and coastal walks.',
    tags: ['Beaches', 'Harbor', 'Sightseeing', 'Outdoor'],
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: 'act-1',
    cityName: 'Paris',
    title: 'Eiffel Tower Summit & Champagne',
    category: 'sightseeing',
    duration: '2.5 hours',
    cost: 3800,
    rating: 4.8,
    reviews: 1240,
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=600&q=80',
    description: 'Take the elevators straight to the summit of the Eiffel Tower for breathtaking panoramic views of Paris, complemented with a glass of champagne.',
    location: 'Champ de Mars, 5 Av. Anatole France',
  },
  {
    id: 'act-2',
    cityName: 'Paris',
    title: 'Louvre Museum Masterpieces Guided Tour',
    category: 'culture',
    duration: '3 hours',
    cost: 4600,
    rating: 4.9,
    reviews: 980,
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=600&q=80',
    description: 'Skip-the-line guided exploration of the world’s largest art museum, viewing the Mona Lisa, Venus de Milo, and Winged Victory.',
    location: 'Rue de Rivoli, 75001 Paris',
  },
  {
    id: 'act-3',
    cityName: 'Paris',
    title: 'Montmartre Gourmet Food & Wine Tasting',
    category: 'food',
    duration: '3.5 hours',
    cost: 7200,
    rating: 4.9,
    reviews: 640,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
    description: 'Walk cobblestone hills of Montmartre stopping at artisan bakeries, cheese fromageries, chocolatiers, and organic wine cellars.',
    location: 'Place du Tertre, Montmartre',
  },
  {
    id: 'act-4',
    cityName: 'Tokyo',
    title: 'Shibuya Crossing & Robot Restaurant Experience',
    category: 'adventure',
    duration: '2 hours',
    cost: 3400,
    rating: 4.7,
    reviews: 1100,
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=600&q=80',
    description: 'Experience the world-famous scramble crossing from Shibuya Sky observation deck, followed by an evening in energetic Shinjuku.',
    location: 'Shibuya Sky & Shinjuku Kabukicho',
  },
  {
    id: 'act-5',
    cityName: 'Tokyo',
    title: 'Tsukiji Outer Market Street Food Tasting',
    category: 'food',
    duration: '2.5 hours',
    cost: 5100,
    rating: 4.9,
    reviews: 820,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
    description: 'Sample fresh sashimi, tamagoyaki omelettes, wagyu skewers, and matcha sweets with an expert local chef.',
    location: 'Tsukiji Outer Market, Chuo City',
  },
  {
    id: 'act-6',
    cityName: 'Rome',
    title: 'Colosseum Underground & Ancient Forum',
    category: 'culture',
    duration: '3 hours',
    cost: 5500,
    rating: 4.9,
    reviews: 1450,
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80',
    description: 'Exclusive access to the gladiator hypogeum (underground tunnels) and arena floor, continuing to Palatine Hill and Roman Forum.',
    location: 'Piazza del Colosseo, 1',
  },
  {
    id: 'act-7',
    cityName: 'Rome',
    title: 'Handmade Pasta & Tiramisu Cooking Class',
    category: 'food',
    duration: '3 hours',
    cost: 6300,
    rating: 4.95,
    reviews: 730,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    description: 'Learn the secrets of making authentic fettuccine and ravioli from scratch paired with fine Italian wine in Trastevere.',
    location: 'Trastevere Culinary Studio',
  },
  {
    id: 'act-8',
    cityName: 'Zurich',
    title: 'Lake Zurich Scenic Boat Cruise & Old Town',
    category: 'sightseeing',
    duration: '2.5 hours',
    cost: 2900,
    rating: 4.8,
    reviews: 490,
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=600&q=80',
    description: 'Cruise tranquil crystal-blue waters surrounded by snow-capped peaks, followed by a stroll past Grossmünster cathedral.',
    location: 'Bürkliplatz Pier, Zurich',
  },
  {
    id: 'act-9',
    cityName: 'Kyoto',
    title: 'Fushimi Inari Torii Gates & Bamboo Grove Sunrise Tour',
    category: 'sightseeing',
    duration: '3.5 hours',
    cost: 2500,
    rating: 4.9,
    reviews: 890,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
    description: 'Beat the crowds at sunrise walking through 10,000 crimson vermilion gates and Arashiyama’s towering green bamboo forest.',
    location: 'Fushimi Inari Taisha, Kyoto',
  },
  {
    id: 'act-10',
    cityName: 'Bali (Ubud)',
    title: 'Tegallalang Rice Terraces & Jungle Swing',
    category: 'adventure',
    duration: '3 hours',
    cost: 2100,
    rating: 4.75,
    reviews: 1300,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
    description: 'Hike through sculpted UNESCO terraced fields and soar above palm canopies on an adrenaline-pumping jungle swing.',
    location: 'Tegallalang, Ubud, Bali',
  },
];

export const INITIAL_TRIPS = [
  {
    id: 'trip-1',
    name: 'Grand European Explorer',
    description: 'A 10-day multi-city journey across the historic monuments of Paris, Alpine serenity of Zurich, and the ancient wonders of Rome.',
    category: 'cultural',
    startDate: '2026-09-10',
    endDate: '2026-09-20',
    targetBudget: 280000,
    currency: 'INR',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
    isPublic: true,
    shareCode: 'EUR-EXPLORER-2026',
    status: 'Upcoming',
    stops: [
      {
        id: 'stop-1',
        cityName: 'Paris',
        country: 'France',
        arrivalDate: '2026-09-10',
        departureDate: '2026-09-13',
        accommodation: {
          hotelName: 'Hôtel Le Marais Paris',
          cost: 42000,
          notes: 'Near Saint-Paul Metro station, breakfast included.',
        },
        transportToNext: {
          mode: 'train',
          provider: 'TGV Lyria',
          cost: 9500,
          duration: '4h 10m',
          notes: 'High-speed scenic train from Gare de Lyon to Zurich HB',
        },
        activities: [
          {
            id: 'act-inst-1',
            dayNumber: 1,
            date: '2026-09-10',
            timeSlot: 'afternoon',
            exactTime: '14:30',
            title: 'Check-in & Stroll in Le Marais',
            category: 'sightseeing',
            cost: 0,
            notes: 'Explore Place des Vosges and local boutiques',
            isCompleted: false,
          },
          {
            id: 'act-inst-2',
            dayNumber: 1,
            date: '2026-09-10',
            timeSlot: 'evening',
            exactTime: '19:00',
            title: 'Seine Sunset River Cruise',
            category: 'sightseeing',
            cost: 2200,
            notes: 'Bateaux Parisiens departure near Eiffel Tower',
            isCompleted: false,
          },
          {
            id: 'act-inst-3',
            dayNumber: 2,
            date: '2026-09-11',
            timeSlot: 'morning',
            exactTime: '09:00',
            title: 'Louvre Museum Masterpieces Tour',
            category: 'culture',
            cost: 4600,
            notes: 'Timed entry ticket at Pyramid entrance',
            isCompleted: false,
          },
          {
            id: 'act-inst-4',
            dayNumber: 2,
            date: '2026-09-11',
            timeSlot: 'afternoon',
            exactTime: '15:00',
            title: 'Montmartre & Sacré-Cœur Food Tasting',
            category: 'food',
            cost: 7200,
            notes: 'Meet guide outside Anvers Metro',
            isCompleted: false,
          },
          {
            id: 'act-inst-5',
            dayNumber: 3,
            date: '2026-09-12',
            timeSlot: 'morning',
            exactTime: '10:00',
            title: 'Eiffel Tower Summit Visit',
            category: 'sightseeing',
            cost: 3800,
            notes: 'Elevator pass to 3rd level',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop-2',
        cityName: 'Zurich',
        country: 'Switzerland',
        arrivalDate: '2026-09-14',
        departureDate: '2026-09-16',
        accommodation: {
          hotelName: 'Swissotel Zurich Old Town',
          cost: 38000,
          notes: 'Short walk to Lake Zurich promenade',
        },
        transportToNext: {
          mode: 'train',
          provider: 'Trenitalia EuroCity',
          cost: 8500,
          duration: '3h 30m',
          notes: 'Direct train to Milano Centrale then Frecciarossa to Rome',
        },
        activities: [
          {
            id: 'act-inst-6',
            dayNumber: 5,
            date: '2026-09-14',
            timeSlot: 'afternoon',
            exactTime: '14:00',
            title: 'Lake Zurich Scenic Boat Tour',
            category: 'relaxation',
            cost: 3200,
            notes: 'Depart from Bürkliplatz pier',
            isCompleted: false,
          },
          {
            id: 'act-inst-7',
            dayNumber: 6,
            date: '2026-09-15',
            timeSlot: 'morning',
            exactTime: '09:30',
            title: 'Uetliberg Mountain Viewpoint Hike',
            category: 'adventure',
            cost: 1500,
            notes: 'Take S10 train from Zurich HB',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop-3',
        cityName: 'Rome',
        country: 'Italy',
        arrivalDate: '2026-09-17',
        departureDate: '2026-09-20',
        accommodation: {
          hotelName: 'Boutique Hotel Navona',
          cost: 45000,
          notes: 'Central location near Piazza Navona and Pantheon',
        },
        transportToNext: null,
        activities: [
          {
            id: 'act-inst-8',
            dayNumber: 8,
            date: '2026-09-17',
            timeSlot: 'morning',
            exactTime: '09:00',
            title: 'Colosseum & Roman Forum Tour',
            category: 'culture',
            cost: 5500,
            notes: 'Gladiator gate underground access',
            isCompleted: false,
          },
          {
            id: 'act-inst-9',
            dayNumber: 9,
            date: '2026-09-18',
            timeSlot: 'afternoon',
            exactTime: '16:00',
            title: 'Handmade Pasta Masterclass',
            category: 'food',
            cost: 6300,
            notes: 'Includes 3-course dinner and unlimited wine',
            isCompleted: false,
          },
        ],
      },
    ],
    expenses: [
      { id: 'exp-1', category: 'stay', amount: 125000, description: 'Hotel stays (Paris, Zurich, Rome)', date: '2026-09-10' },
      { id: 'exp-2', category: 'transport', amount: 58000, description: 'Flights & Inter-city High-Speed Trains', date: '2026-09-10' },
      { id: 'exp-3', category: 'activities', amount: 34300, description: 'Museum passes, tours, and experiences', date: '2026-09-12' },
      { id: 'exp-4', category: 'food', amount: 38000, description: 'Restaurants & Cafe Dining estimate', date: '2026-09-14' },
      { id: 'exp-5', category: 'misc', amount: 12000, description: 'City taxes and local SIM cards', date: '2026-09-11' },
    ],
  },
  {
    id: 'trip-2',
    name: 'Japan Autumn Blossom & Temples',
    description: 'Exploring modern neon marvels of Tokyo, historic geisha streets of Kyoto, and premier culinary markets in Osaka.',
    category: 'adventure',
    startDate: '2026-11-05',
    endDate: '2026-11-15',
    targetBudget: 320000,
    currency: 'INR',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80',
    isPublic: true,
    shareCode: 'JPN-AUTUMN-2026',
    status: 'Upcoming',
    stops: [
      {
        id: 'stop-j1',
        cityName: 'Tokyo',
        country: 'Japan',
        arrivalDate: '2026-11-05',
        departureDate: '2026-11-09',
        accommodation: { hotelName: 'Shinjuku Prince Hotel', cost: 52000, notes: 'Direct train access' },
        transportToNext: { mode: 'train', provider: 'Shinkansen Bullet Train', cost: 12000, duration: '2h 15m', notes: 'Tokaido Shinkansen with Mt Fuji views' },
        activities: [
          { id: 'act-j1', dayNumber: 1, date: '2026-11-05', timeSlot: 'evening', exactTime: '18:00', title: 'Shinjuku & Shibuya Sky Walk', category: 'sightseeing', cost: 3400, notes: 'Golden Gai dinner', isCompleted: false },
          { id: 'act-j2', dayNumber: 2, date: '2026-11-06', timeSlot: 'morning', exactTime: '08:30', title: 'Tsukiji Outer Market Food Tour', category: 'food', cost: 5100, notes: 'Fresh seafood tasting', isCompleted: false },
        ],
      },
      {
        id: 'stop-j2',
        cityName: 'Kyoto',
        country: 'Japan',
        arrivalDate: '2026-11-10',
        departureDate: '2026-11-15',
        accommodation: { hotelName: 'Kyoto Ryokan Gion', cost: 65000, notes: 'Traditional tatami room with onsen' },
        transportToNext: null,
        activities: [
          { id: 'act-j3', dayNumber: 6, date: '2026-11-10', timeSlot: 'morning', exactTime: '07:00', title: 'Fushimi Inari Shrine Sunrise', category: 'sightseeing', cost: 0, notes: 'Hike to summit torii gates', isCompleted: false },
          { id: 'act-j4', dayNumber: 7, date: '2026-11-11', timeSlot: 'morning', exactTime: '10:00', title: 'Arashiyama Bamboo Grove & Tea Ceremony', category: 'culture', cost: 3500, notes: 'Includes matcha tasting', isCompleted: false },
        ],
      },
    ],
    expenses: [
      { id: 'exp-j1', category: 'stay', amount: 117000, description: 'Hotels and Ryokan (9 nights)', date: '2026-11-05' },
      { id: 'exp-j2', category: 'transport', amount: 68000, description: 'International Flights & JR Pass', date: '2026-11-05' },
      { id: 'exp-j3', category: 'activities', amount: 32000, description: 'Tours & Experiences', date: '2026-11-07' },
      { id: 'exp-j4', category: 'food', amount: 46000, description: 'Kaiseki & Street dining', date: '2026-11-08' },
    ],
  },
  {
    id: 'trip-3',
    name: 'Bali Wellness & Tropical Retreat',
    description: 'A relaxing getaway filled with yoga retreats, emerald rice terraces, beach sunsets, and surfing in Bali.',
    category: 'leisure',
    startDate: '2026-06-01',
    endDate: '2026-06-08',
    targetBudget: 120000,
    currency: 'INR',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=80',
    isPublic: false,
    shareCode: 'BALI-SERENE-2026',
    status: 'Upcoming',
    stops: [
      {
        id: 'stop-b1',
        cityName: 'Bali (Ubud)',
        country: 'Indonesia',
        arrivalDate: '2026-06-01',
        departureDate: '2026-06-08',
        accommodation: { hotelName: 'Ubud Jungle Sanctuary Resort', cost: 42000, notes: 'Infinity pool facing forest' },
        transportToNext: null,
        activities: [
          { id: 'act-b1', dayNumber: 1, date: '2026-06-01', timeSlot: 'morning', exactTime: '08:00', title: 'Tegallalang Rice Terraces & Swing', category: 'adventure', cost: 2100, notes: 'Photo spot early morning', isCompleted: false },
          { id: 'act-b2', dayNumber: 2, date: '2026-06-02', timeSlot: 'afternoon', exactTime: '15:00', title: 'Balinese Herbal Spa & Yoga', category: 'relaxation', cost: 4500, notes: 'Traditional healing massage', isCompleted: false },
        ],
      },
    ],
    expenses: [
      { id: 'exp-b1', category: 'stay', amount: 42000, description: 'Villa accommodation (7 nights)', date: '2026-06-01' },
      { id: 'exp-b2', category: 'transport', amount: 36000, description: 'Flights, airport transfers and scooter', date: '2026-06-01' },
      { id: 'exp-b3', category: 'activities', amount: 14000, description: 'Spa, Yoga and Excursions', date: '2026-06-02' },
      { id: 'exp-b4', category: 'food', amount: 16000, description: 'Organic cafes and warungs', date: '2026-06-03' },
    ],
  },
];

export const MOCK_ADMIN_STATS = {
  totalUsers: 14280,
  totalTrips: 38450,
  totalStops: 112800,
  totalActivities: 310500,
  totalBudgetPlanned: 365000000,
  popularDestinations: [
    { name: 'Paris', country: 'France', tripsCount: 8420, growth: '+18%' },
    { name: 'Tokyo', country: 'Japan', tripsCount: 7910, growth: '+24%' },
    { name: 'Rome', country: 'Italy', tripsCount: 6840, growth: '+12%' },
    { name: 'Bali', country: 'Indonesia', tripsCount: 5930, growth: '+31%' },
    { name: 'New York', country: 'USA', tripsCount: 5210, growth: '+9%' },
  ],
  activityCategories: [
    { category: 'Sightseeing & Landmarks', count: 124000, percentage: 40 },
    { category: 'Food & Culinary Experiences', count: 77600, percentage: 25 },
    { category: 'Culture & Museums', count: 46500, percentage: 15 },
    { category: 'Adventure & Outdoor', count: 37200, percentage: 12 },
    { category: 'Relaxation & Spa', count: 24800, percentage: 8 },
  ],
  recentUsers: [
    { id: 'u-101', name: 'Sophia Chen', email: 'sophia.c@example.com', tripsCount: 6, joinedDate: '2026-07-15', status: 'Active', role: 'Traveler' },
    { id: 'u-102', name: 'Liam Davies', email: 'liam.d@example.com', tripsCount: 4, joinedDate: '2026-07-28', status: 'Active', role: 'Traveler' },
    { id: 'u-103', name: 'Elena Rostova', email: 'elena.r@example.com', tripsCount: 11, joinedDate: '2026-08-01', status: 'Active', role: 'Guide' },
    { id: 'u-104', name: 'Marcus Johnson', email: 'marcus.j@example.com', tripsCount: 2, joinedDate: '2026-08-10', status: 'Active', role: 'Traveler' },
    { id: 'u-105', name: 'Amina Al-Mansoor', email: 'amina.m@example.com', tripsCount: 8, joinedDate: '2026-08-18', status: 'Active', role: 'Traveler' },
  ],
};
